import {lazy,Suspense} from 'react'
import {useSelector} from 'react-redux'
import {} from '@/redux/auth/selector'
import { AppContextProvider } from '@/context/appContext'
import PageLoader from '@/components/PageLoader'
import Localization from '@/locale/Localization'
