export const RESET_STATE = 'SETTING_REQUEST_STATE';
export const REQUEST_LOADING = 'SETTING_REQUEST_LOADING';
export const REQUEST_SUCCESS = 'SETTING_REQUEST_SUCCESS';
export const REQUEST_FAILED = 'SETTING_REQUEST_FAILED';
